apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: Yertugan/myproject:latest
        command: ["python"]
        args: [
          "manage.py",
          "runserver",
          "0.0.0.0:8000"
        ]
        ports:
        - name: web
          containerPort: 8000
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: myproject-secret
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myproject-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: myproject-secret
                key: POSTGRES_USER
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: myproject-config
                key: SECRET_KEY