apiVersion: batch/v1
kind: Job
metadata:
  name: myproject-migration
spec:
  template:
    spec:
      containers:
        - name: myproject-migration
          image: Yertugan/myproject:latest
          command: ["python"]
          args: [
            "manage.py",
            "migrate"
          ]
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: myproject-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myproject-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: myproject-secret
                  key: POSTGRES_USER
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: myproject-config
                  key: SECRET_KEY

      restartPolicy: Never
  backoffLimit: 5
